# Generated by Django 6.0.1 on 2026-01-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
