# Generated by Django 6.0.1 on 2026-01-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_donation_transaction_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
